apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: secretworld-app-clone
  labels:
    tekton.dev/pipeline: secretworld-app-clone
spec:
  serviceAccountName: github-bot 
  pipelineRef:
    name: secretworld-app-clone
  params:
    - name: private-github-repo-url
      value: https://github.com/Rajesh6305/Simple-Hello.git
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: pvc-claim-2
